import type { CatalogSyncResult, Part, StockPlacement } from "@/modules/te-lab-components/types";

const timestamp = "2026-07-25T12:00:00.000Z";

function basePart(overrides: Partial<Part> & Pick<Part, "id" | "databaseId" | "entryUuid" | "internalPartNumber">): Part {
  return {
    category: "Passive",
    subcategory: "",
    manufacturer: "",
    manufacturerPartNumber: "",
    displayValue: "",
    mountingType: "through_hole",
    packageType: "",
    description: "",
    attributes: {},
    supplier: "DigiKey",
    supplierSku: "",
    supplierPackaging: "cut_tape",
    productUrl: "",
    datasheetUrl: "",
    defaultUnitOfMeasure: "pcs",
    reorderPoint: null,
    targetQuantity: null,
    partStatus: "active",
    picturePath: "",
    notes: "",
    archived: false,
    legacy: {
      serialNumber: "",
      projectName: "",
      assignedTo: "",
      lifecycleStatus: "",
      workingStatus: "",
      condition: "",
      verifiedInSurvey: false,
      manualEntry: true,
    },
    createdAt: timestamp,
    updatedAt: timestamp,
    ...overrides,
  };
}

const resistor: Part = basePart({
  id: "1",
  databaseId: 1,
  entryUuid: "mock-part-resistor",
  internalPartNumber: "LAB-R-1K0",
  subcategory: "Resistor",
  manufacturer: "Stackpole Electronics",
  manufacturerPartNumber: "CF14JT1K00",
  displayValue: "1 kΩ",
  packageType: "axial",
  description: "Carbon film resistor, 1/4 W",
  attributes: {
    tolerance: { value: "5", unit: "%" },
    powerRating: { value: "0.25", unit: "W" },
  },
  supplierSku: "CF14JT1K00CT-ND",
  productUrl: "https://www.digikey.com/en/products/detail/stackpole-electronics-inc/CF14JT1K00/1741314",
  reorderPoint: 50,
  targetQuantity: 250,
});

const capacitor: Part = basePart({
  id: "2",
  databaseId: 2,
  entryUuid: "mock-part-capacitor",
  internalPartNumber: "LAB-C-100N",
  subcategory: "Capacitor",
  manufacturer: "KEMET",
  manufacturerPartNumber: "C315C104M5U5TA",
  displayValue: "100 nF",
  packageType: "radial",
  description: "MLCC ceramic, X7R-style general purpose",
  attributes: {
    capacitance: { value: "100", unit: "nF" },
    ratedVoltage: { value: "50", unit: "V" },
  },
  supplierSku: "399-4151-ND",
  reorderPoint: 25,
  targetQuantity: 100,
});

const transistor: Part = basePart({
  id: "3",
  databaseId: 3,
  entryUuid: "mock-part-transistor",
  internalPartNumber: "LAB-Q-3904",
  category: "Semiconductor",
  subcategory: "BJT",
  manufacturer: "onsemi",
  manufacturerPartNumber: "2N3904BU",
  displayValue: "2N3904",
  packageType: "TO-92",
  description: "NPN general-purpose switching transistor",
  attributes: {
    deviceType: { value: "NPN", unit: "" },
    voltageRating: { value: "40", unit: "V" },
  },
  supplierSku: "2N3904BU-ND",
});

const led: Part = basePart({
  id: "4",
  databaseId: 4,
  entryUuid: "mock-part-led",
  internalPartNumber: "LAB-D-LED-RED",
  category: "Optoelectronics",
  subcategory: "LED",
  manufacturer: "Kingbright",
  manufacturerPartNumber: "WP7113ID",
  displayValue: "Red 5 mm",
  packageType: "T-1 3/4",
  description: "High-efficiency red indicator LED",
  attributes: {
    color: { value: "Red", unit: "" },
    forwardVoltage: { value: "2.0", unit: "V" },
  },
  supplierSku: "754-1264-ND",
  reorderPoint: 20,
  targetQuantity: 100,
});

const mcu: Part = basePart({
  id: "5",
  databaseId: 5,
  entryUuid: "mock-part-mcu",
  internalPartNumber: "LAB-U-STM32",
  category: "Semiconductor",
  subcategory: "MCU",
  manufacturer: "STMicroelectronics",
  manufacturerPartNumber: "STM32F103C8T6",
  displayValue: "STM32F103C8",
  mountingType: "smd",
  packageType: "LQFP-48",
  description: "ARM Cortex-M3 MCU, 64 KB flash",
  attributes: {
    flash: { value: "64", unit: "KB" },
    core: { value: "Cortex-M3", unit: "" },
  },
  supplier: "Mouser",
  supplierSku: "511-STM32F103C8T6",
  supplierPackaging: "tray",
  reorderPoint: 2,
  targetQuantity: 10,
});

const connector: Part = basePart({
  id: "6",
  databaseId: 6,
  entryUuid: "mock-part-usb",
  internalPartNumber: "LAB-J-USB-C",
  category: "Connector",
  subcategory: "USB",
  manufacturer: "Amphenol ICC",
  manufacturerPartNumber: "12401598E4#2A",
  displayValue: "USB-C receptacle",
  mountingType: "smd",
  packageType: "SMT",
  description: "USB Type-C 16-pin mid-mount receptacle",
  attributes: {
    gender: { value: "Receptacle", unit: "" },
    ports: { value: "1", unit: "" },
  },
  supplierSku: "609-5247-1-ND",
  reorderPoint: 5,
  targetQuantity: 25,
});

const placements: StockPlacement[] = [
  {
    placementUuid: "mock-placement-r-main",
    partUuid: resistor.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 2,
    rowIndex: 6,
    freeformPosition: "",
    quantity: 180,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "counted",
    lastCountedAt: timestamp,
    lastCountedBy: "Demo",
    notes: "",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-r-desk",
    partUuid: resistor.entryUuid,
    containerUuid: "mock-container-desk",
    columnIndex: 1,
    rowIndex: 3,
    freeformPosition: "",
    quantity: 25,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "uncounted",
    lastCountedAt: null,
    lastCountedBy: "",
    notes: "",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-c-main",
    partUuid: capacitor.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 2,
    rowIndex: 6,
    freeformPosition: "",
    quantity: 40,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "uncounted",
    lastCountedAt: null,
    lastCountedBy: "",
    notes: "",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-led-main",
    partUuid: led.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 8,
    rowIndex: 1,
    freeformPosition: "",
    quantity: 12,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "counted",
    lastCountedAt: timestamp,
    lastCountedBy: "Demo",
    notes: "Below reorder point",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-mcu-main",
    partUuid: mcu.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 12,
    rowIndex: 3,
    freeformPosition: "",
    quantity: 6,
    unitOfMeasure: "pcs",
    packaging: "tray",
    lotCode: "A2401",
    dateCode: "2412",
    condition: "new",
    countState: "counted",
    lastCountedAt: timestamp,
    lastCountedBy: "Demo",
    notes: "",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-usb-main",
    partUuid: connector.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 15,
    rowIndex: 5,
    freeformPosition: "",
    quantity: 3,
    unitOfMeasure: "pcs",
    packaging: "reel_cut",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "uncounted",
    lastCountedAt: null,
    lastCountedBy: "",
    notes: "Low stock",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const MOCK_CATALOG: CatalogSyncResult = {
  dbPath: "Mock Lab Components catalog",
  parts: [resistor, capacitor, transistor, led, mcu, connector],
  storageAreas: [
    {
      areaUuid: "mock-area-main",
      name: "Main Lab",
      areaType: "lab",
      owner: "TE",
      description: "Main component storage",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      areaUuid: "mock-area-desk",
      name: "Desk — Alex",
      areaType: "desk",
      owner: "Alex",
      description: "Desk-side organizer",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  storageContainers: [
    {
      containerUuid: "mock-container-main",
      areaUuid: "mock-area-main",
      name: "Component Cabinet 1",
      containerType: "cabinet",
      gridEnabled: true,
      rowCount: 8,
      columnCount: 28,
      rowStart: 1,
      origin: "top_left",
      description: "Excel-style drawer grid",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      containerUuid: "mock-container-desk",
      areaUuid: "mock-area-desk",
      name: "Organizer 1",
      containerType: "organizer",
      gridEnabled: true,
      rowCount: 6,
      columnCount: 6,
      rowStart: 1,
      origin: "top_left",
      description: "",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  stockPlacements: placements,
  summaries: [
    {
      partUuid: resistor.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 205 }],
      stockStatus: "in_stock",
    },
    {
      partUuid: capacitor.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 40 }],
      stockStatus: "in_stock",
    },
    {
      partUuid: transistor.entryUuid,
      totals: [],
      stockStatus: "no_stock",
    },
    {
      partUuid: led.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 12 }],
      stockStatus: "low_stock",
    },
    {
      partUuid: mcu.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 6 }],
      stockStatus: "in_stock",
    },
    {
      partUuid: connector.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 3 }],
      stockStatus: "low_stock",
    },
  ],
  counts: {
    activeParts: 6,
    archivedParts: 0,
    totalParts: 6,
    noStock: 1,
    lowStock: 2,
    unitReview: 0,
  },
  migration: {
    schemaVersion: 2,
    required: false,
    legacyEntryCount: 0,
    catalogInitialized: true,
    message: "Lab Components catalog schema v2 is ready.",
  },
  shared: {
    available: true,
    canModify: true,
    enabled: false,
    message: "Mock catalog data",
    mutationMode: "local",
  },
};
