import type { CatalogSyncResult, Part, StockPlacement } from "@/modules/te-lab-components/types";

const timestamp = "2026-07-25T12:00:00.000Z";

const resistor: Part = {
  id: "1",
  databaseId: 1,
  entryUuid: "mock-part-resistor",
  internalPartNumber: "LAB-R-001",
  category: "Passive",
  subcategory: "Resistor",
  manufacturer: "Stackpole Electronics",
  manufacturerPartNumber: "CF14JT1K00",
  displayValue: "1 kΩ",
  mountingType: "through_hole",
  packageType: "axial",
  description: "Carbon film resistor",
  attributes: {
    tolerance: { value: "5", unit: "%" },
    powerRating: { value: "0.25", unit: "W" },
  },
  supplier: "DigiKey",
  supplierSku: "CF14JT1K00CT-ND",
  supplierPackaging: "cut_tape",
  productUrl: "https://www.digikey.com/en/products/detail/stackpole-electronics-inc/CF14JT1K00/1741314",
  datasheetUrl: "",
  defaultUnitOfMeasure: "pcs",
  reorderPoint: 50,
  targetQuantity: 250,
  partStatus: "active",
  picturePath: "",
  notes: "Mock catalog example",
  archived: false,
  legacy: {
    serialNumber: "",
    projectName: "",
    assignedTo: "",
    lifecycleStatus: "",
    workingStatus: "",
    condition: "",
    verifiedInSurvey: false,
    manualEntry: true,
  },
  createdAt: timestamp,
  updatedAt: timestamp,
};

const capacitor: Part = {
  ...resistor,
  id: "2",
  databaseId: 2,
  entryUuid: "mock-part-capacitor",
  internalPartNumber: "LAB-C-001",
  subcategory: "Capacitor",
  manufacturer: "KEMET",
  manufacturerPartNumber: "C315C104M5U5TA",
  displayValue: "100 nF",
  packageType: "radial",
  description: "Ceramic capacitor",
  attributes: {
    capacitance: { value: "100", unit: "nF" },
    ratedVoltage: { value: "50", unit: "V" },
  },
  supplierSku: "399-4151-ND",
  productUrl: "",
  reorderPoint: 25,
  targetQuantity: 100,
};

const transistor: Part = {
  ...resistor,
  id: "3",
  databaseId: 3,
  entryUuid: "mock-part-transistor",
  internalPartNumber: "LAB-Q-001",
  category: "Semiconductor",
  subcategory: "BJT",
  manufacturer: "onsemi",
  manufacturerPartNumber: "2N3904BU",
  displayValue: "2N3904",
  packageType: "TO-92",
  description: "NPN general-purpose transistor",
  attributes: {
    deviceType: { value: "NPN", unit: "" },
    voltageRating: { value: "40", unit: "V" },
  },
  supplierSku: "2N3904BU-ND",
  reorderPoint: null,
  targetQuantity: null,
};

const placements: StockPlacement[] = [
  {
    placementUuid: "mock-placement-r-main",
    partUuid: resistor.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 2,
    rowIndex: 6,
    freeformPosition: "",
    quantity: 100,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "counted",
    lastCountedAt: timestamp,
    lastCountedBy: "Demo",
    notes: "",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-r-desk",
    partUuid: resistor.entryUuid,
    containerUuid: "mock-container-desk",
    columnIndex: 1,
    rowIndex: 3,
    freeformPosition: "",
    quantity: 20,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "uncounted",
    lastCountedAt: null,
    lastCountedBy: "",
    notes: "",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    placementUuid: "mock-placement-c-main",
    partUuid: capacitor.entryUuid,
    containerUuid: "mock-container-main",
    columnIndex: 2,
    rowIndex: 6,
    freeformPosition: "",
    quantity: 50,
    unitOfMeasure: "pcs",
    packaging: "bag",
    lotCode: "",
    dateCode: "",
    condition: "new",
    countState: "uncounted",
    lastCountedAt: null,
    lastCountedBy: "",
    notes: "Shared bin example",
    archived: false,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const MOCK_CATALOG: CatalogSyncResult = {
  dbPath: "Mock Lab Components catalog",
  parts: [resistor, capacitor, transistor],
  storageAreas: [
    {
      areaUuid: "mock-area-main",
      name: "Main Lab",
      areaType: "lab",
      owner: "TE",
      description: "Main component storage",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      areaUuid: "mock-area-desk",
      name: "Desk — Alex",
      areaType: "desk",
      owner: "Alex",
      description: "Desk-side organizer",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  storageContainers: [
    {
      containerUuid: "mock-container-main",
      areaUuid: "mock-area-main",
      name: "Component Cabinet 1",
      containerType: "cabinet",
      gridEnabled: true,
      rowCount: 8,
      columnCount: 28,
      rowStart: 1,
      origin: "top_left",
      description: "Excel-style drawer grid",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
    {
      containerUuid: "mock-container-desk",
      areaUuid: "mock-area-desk",
      name: "Organizer 1",
      containerType: "organizer",
      gridEnabled: true,
      rowCount: 6,
      columnCount: 6,
      rowStart: 1,
      origin: "top_left",
      description: "",
      archived: false,
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
  stockPlacements: placements,
  summaries: [
    {
      partUuid: resistor.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 120 }],
      stockStatus: "in_stock",
    },
    {
      partUuid: capacitor.entryUuid,
      totals: [{ unitOfMeasure: "pcs", quantity: 50 }],
      stockStatus: "in_stock",
    },
    {
      partUuid: transistor.entryUuid,
      totals: [],
      stockStatus: "no_stock",
    },
  ],
  counts: {
    activeParts: 3,
    archivedParts: 0,
    totalParts: 3,
    noStock: 1,
    lowStock: 0,
    unitReview: 0,
  },
  migration: {
    schemaVersion: 2,
    required: false,
    legacyEntryCount: 0,
    catalogInitialized: true,
    message: "Lab Components catalog schema v2 is ready.",
  },
  shared: {
    available: true,
    canModify: true,
    enabled: false,
    message: "Mock catalog data",
    mutationMode: "local",
  },
};
